name: Publish

on:
    push:
        branches: [main]

permissions:
    contents: write

jobs:
    deploy: 
        runs-on: ubuntu-latest
        environment: github-pages
        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 14.x
              uses: actions/setup-node@v2
              with:
                node-version: 14.x
            - name: Install and Build 🔧
              run: |
                npm i 
                npm run predeploy
              env:
                REACT_APP_FIREBASE_API_KEY:  ${{ secrets.REACT_APP_FIREBASE_API_KEY }}
                REACT_APP_FIREBASE_AUTH_DOMAIN:  ${{ secrets.REACT_APP_FIREBASE_AUTH_DOMAIN }}
                REACT_APP_FIREBASE_PROJECT_ID:  ${{ secrets.REACT_APP_FIREBASE_PROJECT_ID }}
                REACT_APP_FIREBASE_STORAGE_BUCKET:  ${{ secrets.REACT_APP_FIREBASE_STORAGE_BUCKET }}
                REACT_APP_FIREBASE_MESSAGING_SENDER_ID:  ${{ secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID }}
                REACT_APP_FIREBASE_APP_ID:  ${{ secrets.REACT_APP_FIREBASE_APP_ID }}
                REACT_APP_FIREBASE_MEASUREMENT_ID:  ${{ secrets.REACT_APP_FIREBASE_MEASUREMENT_ID }}
                REACT_APP_FIREBASE_RECAPTCHA_PROVIDER_KEY:  ${{ secrets.REACT_APP_FIREBASE_RECAPTCHA_PROVIDER_KEY }}
            - name: Deploy 🚀
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                branch: gh-pages
                folder: build 

